[project]
name = "fastapi-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Manime016", email = "imanikanta016@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "fastapi-users[sqlalchemy]>=15.0.5",
    "imagekitio>=5.10.0",
    "pymysql>=1.2.3",
    "python-dotenv>=1.2.3",
    "requests>=2.32.0",
    "streamlit>=1.50.0",
    "uvicorn[standard]>=0.54.0",
]

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
